name: ${APP_NAME}

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      target: backend
    ports:
      - ${APP_PORT}:${APP_PORT}
    tty: true
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
      - venv:/app/.venv

  frontend:
    build:
      dockerfile: Dockerfile
      context: .
      target: frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    entrypoint: [ 'npm', 'run', 'dev' ]
    environment:
      APP_ENV: ${APP_ENV:-development}
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env
      - node_modules:/app/node_modules

volumes:
  venv:
  node_modules:
