"""Init jobs table

Revision ID: b1de7453b950
Revises:
Create Date: 2026-05-17 12:16:25.312815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1de7453b950'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'GRAPH_BUILDING', 'DETECTING', 'SCORING', 'LAYOUT', 'SAVING', 'COMPLETED', 'FAILED', name='job_status'), server_default='PENDING', nullable=False),
    sa.Column('format', postgresql.ENUM('IBM', 'CUSTOM', name='upload_format'), server_default='IBM', nullable=False),
    sa.Column('user_ip', sa.String(length=45), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ladybug_ref', sa.Text(), nullable=True),
    sa.Column('detector_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
